---
server:
  port: 8085
spring:
  cloud:
    gateway:
      routes:
        - id: userservice
          uri: http://localhost:8081
          predicates:
            - Path=/userservice/**
        - id: backoffice
          uri: http://localhost:8082
          predicates:
            - Path=/backoffice/**